CREATE DATABASE jack;

CREATE TABLE jack.houses (
  ID             INTEGER AUTO_INCREMENT PRIMARY KEY,
  COST           INTEGER NOT NULL,
  PRICE          INTEGER NOT NULL,
  ADRESS         VARCHAR(60) NOT NULL,
  RENT           BOOLEAN DEFAULT FALSE,
  BUILDING_DATE DATE,
  SALED_DATE    DATE
);

CREATE TABLE jack.renters (
  ID           INTEGER AUTO_INCREMENT PRIMARY KEY,
  HOUSE_ID     INTEGER NOT NULL,
  NAME         VARCHAR(60) NOT NULL,
  RENTED_DATE DATE,
  EXPIRE_DATE DATE,
  DAYLY_RENT  BOOLEAN DEFAULT FALSE,
  RATE         INTEGER NOT NULL,
  FOREIGN KEY (HOUSE_ID) REFERENCES jack.houses (id) ON DELETE CASCADE
);

CREATE TABLE jack.payments (
  HOUSE_ID     INTEGER NOT NULL,
  DATE          DATE NOT NULL,
  SUMM          INTEGER NOT NULL,
  FOREIGN KEY  (HOUSE_ID) REFERENCES jack.houses (id) ON DELETE CASCADE
)
